### ISSUE TITLE
can upload sln pro? please

### ISSUE THREAD

**Issue by ggg4566** [helpsystems/nanodump#10]
Can upload sln project? vs2015 compile, output many error ... 
thanks !

**Comment by S4ntiagoP** [comment]
Hey there,
If you want to compile your own version of nanodump, you need to use MinGW on Linux.
Once you have that installed, just run `make`  inside of the nanodump folder.
Cheers

**Comment by ggg4566** [comment]
thanks!

**Comment by w1u0u1** [comment]
> Can upload sln project? vs2015 compile, output many error ... thanks !

https://github.com/w1u0u1/nanodump

**Comment by ggg4566** [comment]
> > Can upload sln project? vs2015 compile, output many error ... thanks !
> 
> https://github.com/w1u0u1/nanodump

good boy :) 🐩  thank you
