### ISSUE TITLE
NtReadVirtualMemory, error

### ISSUE THREAD

**Issue by lengjibo** [helpsystems/nanodump#11]
Environment is Windows 10 + Kaspersky Total Security.

NtReadVirtualMemory, status: 0xc0000022 

If you need the environment, here is the download link

https://trial.s.kaspersky-labs.com/registered/vvzkph9ftg3ws2zhfhll/3436353730347c44454c7c32_26155/kts21.3.10.391abzh-Hans_26155.exe

**Comment by S4ntiagoP** [comment]
Appreciate it, but if nanodump can't to read LSASS while kaspersky is used, that is not an issue on nanodump, as there is nothing to fix. I will take a look though.
If there is a bypass to whatever protection kaspersky uses, PRs are welcome.
