### ISSUE TITLE
LSASS process not found

### ISSUE THREAD

**Issue by nemesis7331** [helpsystems/nanodump#14]
I'm using the same exe on the same cloned VM, first one works, second one has an EDR and I get this:

```
>whoami /all
...
SeDebugPrivilege                Debug programs                            Disabled

>tasklist
...
lsass.exe                      728 Services                   0     16,536 K

>nanodump.x64.exe -w dump
The LSASS process was not found. Are you elevated?
```

I'm guessing the EDR is doing something, but it has detected nothing, any idea? 

p.s. the VM is obviously isolated from internet/cloud

**Comment by S4ntiagoP** [comment]
Hello! Are you running as admin?

**Comment by nemesis7331** [comment]
Hello :)
yes, also same user as the other VM

**Comment by S4ntiagoP** [comment]
try with
`nanodump -w dump -p 728`

**Comment by nemesis7331** [comment]
wow hidden command! 

```
>nanodump.x64.exe -w dump -p 728
Failed to read LSASS, status: 0xc0000022
```

**Comment by S4ntiagoP** [comment]
haha that is the only hidden command, you can check if you don't trust me.
Looks like you can't read LSASS, that happens with some EDRs, in my experience, if you load nanodump as an SSP, it works on those cases.
I'm still trying to figure out how the manage to prevent you from reading LSASS

**Comment by nemesis7331** [comment]
It works thanks! 
I'll let you know if I find out anything

**Comment by S4ntiagoP** [comment]
Awesome! I'm glad.
Out of curiosity, what EDR is it?

**Comment by nemesis7331** [comment]
Checkpoint, but I've also seen a similar behaviour with Sophos in the past

**Comment by S4ntiagoP** [comment]
Ok thanks, good to know.
I changed the error messages so this is easier to diagnose in the future: https://github.com/helpsystems/nanodump/commit/f718c2cb41a9bc3c4a28d2b7dffbc300089b4967
I'm closing this, thanks for letting me know, I will try to find out what is going on exactly and see if I can do anything about it.
