### ISSUE TITLE
source/utils.c(264): error C2065: 'ProcessInstrumentationCallback': undeclared identifier

### ISSUE THREAD

**Issue by johnjohnsp1** [helpsystems/nanodump#16]
hello,
getting this error during the compile steps:

C:\temp\nanodump>nmake -f Makefile.msvc

Microsoft (R) Program Maintenance Utility Version 14.29.30140.0
Copyright (C) Microsoft Corporation.  All rights reserved.

###### RELEASE ######
        ML64 /c source/syscalls-asm.asm /link /NODEFAULTLIB /RELEASE /MACHINE:X64
Microsoft (R) Macro Assembler (x64) Version 14.29.30140.0
Copyright (C) Microsoft Corporation.  All rights reserved.

 Assembling: source/syscalls-asm.asm
        cl.exe -DNANO -DEXE -Zp8 -c -nologo -Gy -Os -O1 -GR- -EHa -Oi -GS- -I include source/dinvoke.c source/utils.c source/handle.c source/modules.c source/syscalls.c source/token_priv.c source/malseclogon.c source/nanodump.c source/entry.c
dinvoke.c
utils.c
source/utils.c(264): error C2065: 'ProcessInstrumentationCallback': undeclared identifier
handle.c
modules.c
syscalls.c
token_priv.c
malseclogon.c
nanodump.c
entry.c
Generating Code...
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe"' : return code '0x2'
Stop.

any ideas or i do something wrong ?
thanks

**Comment by S4ntiagoP** [comment]
I added that feature and did not test it in the MSVC compiler, I will fix it soon, in the meanwhile, you can use the MINGW compiler in Linux.

**Comment by johnjohnsp1** [comment]
Thanks for the reply, will make it on linux

**Comment by S4ntiagoP** [comment]
ok done,
thanks for reporting!
