### ISSUE TITLE
dumpfile parse error

### ISSUE THREAD

**Issue by ggg4566** [helpsystems/nanodump#20]
Nano dump file size is only 9M mimikatz and pypykatz cannot be parsed normally . Procdump dumpfile is 35M

**Comment by S4ntiagoP** [comment]
Hello @ggg4566 , is the procdump dump parsed correctly?
The difference in size is normal. Also, try updating pypykatz to the latest version and try again.

**Comment by ggg4566** [comment]
> Hello @ggg4566 , is the procdump dump parsed correctly? The difference in size is normal. Also, try updating pypykatz to the latest version and try again.

pypykatz is the latest version, procdump dump can parse normal.  Dumpfile cannot be parsed normally on win7 and win10
<img width="808" alt="image" src="https://user-images.githubusercontent.com/7532477/165687355-65524a33-9c02-47e6-8e40-8605e40dbde3.png">

**Comment by ggg4566** [comment]
@S4ntiagoP Use old version nanodump dump file can't be parsed normally, and the dumpfile grabbed on my colleague's computer is also the same result

**Comment by S4ntiagoP** [comment]
It is failing because of the invalid signature, restore it by running this on linux:
```bash scripts/restore_signature.sh mem.dump```

**Comment by ggg4566** [comment]
> It is failing because of the invalid signature, restore it by running this on linux: `bash scripts/restore_signature.sh mem.dump`

thank you! nice:)
