### ISSUE TITLE
not lucky with BEST

### ISSUE THREAD

**Issue by protrading104** [helpsystems/nanodump#26]
![screen](https://i.imgur.com/UIxlqXz.png)
without bitdefender everything works
is there any way to solve this ?

**Comment by S4ntiagoP** [comment]
Hey there, no clue what Bitdefender is doing, maybe DefineDosDeviceW is hooked by the solution and that is why it fails, hard to know.
Anyway, detections by EDRs are not really an issue for me, given that there is no "bug" to fix.
