### ISSUE TITLE
malseclogon_trigger_lock leaks process and thread handles returned from  CreateProcessWithTokenW/CreateProcessWithLogonW

### ISSUE THREAD

**Issue by JohnLaTwC** [helpsystems/nanodump#28]
These calls to `CreateProcessWithTokenW` and `CreateProcessWithLogonW` do not close the process and thread handles returned in the `procInfo` parameter.

See: https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithtokenw
> Handles in [PROCESS_INFORMATION](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-process_information) must be closed with the [CloseHandle](https://learn.microsoft.com/en-us/windows/desktop/api/handleapi/nf-handleapi-closehandle) function when they are no longer needed.

```diff
            success = CreateProcessWithTokenW(
                handle_list->Handle[i],
                0,
                NULL,
                cmdline,
                0,
                NULL,
                NULL,
                (LPSTARTUPINFOW)&startInfo,
!                &procInfo);   <<< Process and thread handles not closed
            if (success)
            {
                break;
            }
        }
    }
    else
    {
        CreateProcessWithLogonW(
            NANODUMP_USER,
            NANODUMP_DOMAIN,
            NANODUMP_PASSWD,
            LOGON_NETCREDENTIALS_ONLY,
            NULL,
            cmdline,
            0,
            NULL,
            NULL,
            (LPSTARTUPINFOW)&startInfo,
!            &procInfo);   <<< Process and thread handles not closed
```
https://github.com/helpsystems/nanodump/blob/08dd0da278b1e3d9a9a3ddfc8f5bb7491bd546ad/source/malseclogon.c#L515

**Comment by S4ntiagoP** [comment]
Thanks man, I really don't like handle leaks.
This has now been fixed: https://github.com/helpsystems/nanodump/commit/f25e32e40fbc874a1b9e6fab2224b6a649c577c7
