### ISSUE TITLE
tiny correctness bug in snapshot_process()

### ISSUE THREAD

**Issue by JohnLaTwC** [helpsystems/nanodump#29]
This is a tiny correctness bug. 

The function design of `snapshot_process` is such that `hProcess` is always clobbered when calling the function. As such, `snapshot_process` must always close the handle otherwise it will result in a handle leak of the passed in hProcess.
```
    // avoid reading LSASS directly by making a snapshot
    if (snapshot_lsass)
    {
        hProcess = snapshot_process(
            hProcess,
            PhSnapshot);
        if (!hProcess)
            goto cleanup;
    }
```

There are two error paths that could lead to such a leakage. I could not find any circumstance where the first one would manifest in the code as written. The second one would only happen if PssNtCaptureSnapshot could not be resolved dynamically (perhaps only possible on out of support target OSes).

```diff
// create a snapshot of the LSASS process
HANDLE snapshot_process(
    IN HANDLE hProcess,
    OUT PHANDLE hSnapshot)
{
    BOOL ret_val = FALSE;
    PssNtCaptureSnapshot_t PssNtCaptureSnapshot;
    PssNtQuerySnapshot_t PssNtQuerySnapshot;
    HANDLE hCloneProcess = NULL;
    DWORD process_flags = 0;
    DWORD thread_flags = 0;
    DWORD error_code = 0;

    if (!hProcess || !hSnapshot)
!        goto cleanup;   <<< hProcess input parameter NOT closed here

    // find the address of PssNtCaptureSnapshot dynamically
    PssNtCaptureSnapshot = (PssNtCaptureSnapshot_t)(ULONG_PTR)get_function_address(
        get_library_address(NTDLL_DLL, TRUE),
        PssNtCaptureSnapshot_SW2_HASH,
        0);
    if (!PssNtCaptureSnapshot)
    {
        api_not_found("PssNtCaptureSnapshot");
!        goto cleanup;   <<< hProcess input parameter NOT closed here
    }

    *hSnapshot    = NULL;
    process_flags = PROCESS_PPSCAPTURESNAPSHOT_PERMISSIONS;
    thread_flags  = THREAD_PPSCAPTURESNAPSHOT_PERMISSIONS;

    error_code = PssNtCaptureSnapshot(
        hSnapshot,
        hProcess,
        process_flags,
        thread_flags);

!    NtClose(hProcess); hProcess = NULL;  <<< hProcess input parameter closed here

```

A solution would be to always ensure that `hProcess` is closed on every exit from `snapshot_process`

https://github.com/helpsystems/nanodump/blob/07e44d2aa2f97cd298b2063fc344999840c8d2a7/source/handle.c#L421

**Comment by S4ntiagoP** [comment]
Hey man!
I greatly appreciate you looking into the code closely enough as to find stuff like that. I care a lot about this kind of bugs, which can be elusive and hard to find.

That being said, are you sure this is really a bug?
Look at the `cleanup` section:
```c
cleanup:
    if (hProcess)
        NtClose(hProcess);
    if (!ret_val && *hSnapshot)
        NtClose(*hSnapshot);
    if (!ret_val && hCloneProcess)
        NtClose(hCloneProcess);

    if (ret_val)
        return hCloneProcess;
    else
        return NULL;
```
If `hProcess` is set, then it will be closed, regardless if the function succeed or not.

Please let me know that you think 😃

**Comment by JohnLaTwC** [comment]
Looking at the cleanup routine, I agree with you.

I first thought this might be the only place that it is closed, but I see that it is also closed in cleanup.  No bug! 👍
https://github.com/helpsystems/nanodump/blob/07e44d2aa2f97cd298b2063fc344999840c8d2a7/source/handle.c#L992

**Comment by S4ntiagoP** [comment]
thanks again for looking at the code!
