### ISSUE TITLE
Can not find load_ssp

### ISSUE THREAD

**Issue by minhnt02** [helpsystems/nanodump#35]
I am facing some issues while testing nanodump on Kaspersky Antivirus. Currently, I find that using nanodump_ssp for dumping after retrieving the Cobalt Strike session is the most stable. However, the nanodump_ssp DLL file gets deleted by Kaspersky if file protection mode is enabled. I have found a solution using load_ssp to avoid writing the file to disk, but I couldn’t find any documentation on 'load_ssp.' Is there a solution to the current problem or a more effective alternative?

**Comment by S4ntiagoP** [comment]
Hey there,
`load_ssp` has been replaced by `nanodump_ssp`, I have updated the readme to reflect that. If the DLL is being detected, try modifying it or writing your own. There isn't much I can do on my own as detection is not an issue.
Have fun!
