### ISSUE TITLE
NtReadVirtualMemory, status: 0xc0000022

### ISSUE THREAD

**Issue by gitnefergit** [helpsystems/nanodump#4]
Environment is Windows 10 + Kaspersky Total Security.
That's totally not a "you" problem, but in your blog i read "A Red Team Approach to Minidumps". Maybe you can nudge me to solve this problem?

**Comment by physics-sec** [comment]
0xc0000022 means STATUS_ACCESS_DENIED, are you elevated? If you are, maybe LSASS is running as [PPL](https://itm4n.github.io/lsass-runasppl/) and thus cannot be read in this way (I might add a detection for this in the near future)

**Comment by S4ntiagoP** [comment]
0xc0000022 means STATUS_ACCESS_DENIED, are you elevated? If you are, maybe LSASS is running as PPL and thus cannot be read in this way (I might add a detection for this in the near future)
I'm closing this for now, feel free to continue to comment here

**Comment by gitnefergit** [comment]
I'm in elevated context. RunasPPL=0
When i'm disable Kaspersky , all works fine.

**Comment by S4ntiagoP** [comment]
I recently modified how syscalls are implemented, so that they appear to come from _ntdll_ and not from _nanodump_.
Give it a try again and let me know how it goes.
I don't have Kaspersky to play arround so I don't really know what they might be doing.

**Comment by gitnefergit** [comment]
Same problem.

**Comment by S4ntiagoP** [comment]
In [this](https://support.kaspersky.com/KESWin/11/en-US/158231.htm) fom Kaspersky page you can read:
```
In the System processes memory protection section, select the Enable system process memory protection check box if you want Kaspersky Endpoint Security to block external processes that attempt to access system processes.
```
I have no idea how the can deny access to a syscall like NtReadVirtualMemory, may be with a syscall callback hook like [this](https://winternl.com/detecting-manual-syscalls-from-user-mode/)? maybe with some kernel driver magic, not sure if that is possible.
As I said, without access to the environment I can't do much

**Comment by lengjibo** [comment]
If you need the environment, here is the download link

https://trial.s.kaspersky-labs.com/registered/vvzkph9ftg3ws2zhfhll/3436353730347c44454c7c32_26155/kts21.3.10.391abzh-Hans_26155.exe

**Comment by S4ntiagoP** [comment]
Hello @gitnefergit and @lengjibo 
I tested the new SSP feature against Kaspersky Total Security and seems to work fine.
I'm still changing the implementation here and there so the feature might not be 100% stable.
Give it a try if you want.
Cheers
