### ISSUE TITLE
Issues with nanodump in cobalt strike

### ISSUE THREAD

**Issue by ScriptIdiot** [helpsystems/nanodump#5]
download [id: -775643611] closed: Missed start message/metadata.

May I know how to solve this? Thanks

**Comment by S4ntiagoP** [comment]
Hello!
That means you are losing requests.
If you are using a redirector, have you read [this](https://github.com/helpsystems/nanodump#https-redirectors)?
If not, it could be really bad internet or some middle-ware or firewall blocking specific requests.

**Comment by ScriptIdiot** [comment]
ah i overlooked! thanks a lot!

**Comment by S4ntiagoP** [comment]
great 😄
