### ISSUE TITLE
what is "cool SW2_SEED"

### ISSUE THREAD

**Issue by huai201208** [helpsystems/nanodump#6]
I am more confused about what this means.
"cool SW2_SEED"

**Comment by S4ntiagoP** [comment]
I just wrote "1337C0DE" [here](https://github.com/helpsystems/nanodump/blob/main/include/syscalls.h#L12)
nothing special, It is usually a random number generated by syswhispers2 [here](https://github.com/jthuraisamy/SysWhispers2/blob/main/syswhispers.py#L12).
