### ISSUE TITLE
WIN7 Failed

### ISSUE THREAD

**Issue by TryA9ain** [helpsystems/nanodump#8]
### Target iInformation
Windows 7 Ultimate (x64)

I use the .exe version to run nanodump

![image](https://user-images.githubusercontent.com/51145610/144351148-2e3c8d9c-16ef-4440-baa3-28a7333666c1.png)

then I downloaded the minidump and Recover invalid signatures

![image](https://user-images.githubusercontent.com/51145610/144351218-5d2b39d9-d5cd-45de-9974-64a4cc60b1e1.png)

I use Kali pypykatz, But it failed

![image](https://user-images.githubusercontent.com/51145610/144351282-be431c6f-34fc-4d8d-a789-094eecfa9d61.png)

**Comment by S4ntiagoP** [comment]
Hey there,
I will get a Win7 VM and try it myself.
In the mean time, why don't you try with the latest version of pypykatz which is "0.5.2" (clone the repo and compile it locally).

**Comment by S4ntiagoP** [comment]
yep, this is a legitimate issue, thanks for reporting it!
I will investigate and try o find what's wrong

**Comment by S4ntiagoP** [comment]
I found the issue, it is fixed in [this](https://github.com/helpsystems/nanodump/commit/0067df19f210353b5493ddb6a49f3ac7cdddd80a) commit.
The thing is that I was setting the field `TimeDateStamp` to 0 on every DLL that was dumped. Aparently this field is important in Windows7 but not in Windows 10.
Thank you very much for finding and reporting this!

**Comment by S0me1-dev** [comment]
![image](https://github.com/fortra/nanodump/assets/63853227/7f2bc0ba-237f-4508-8b48-658f4556662e) 
![image](https://github.com/fortra/nanodump/assets/63853227/8afa5adf-f72a-46bf-8aa3-a96846ddd6b4)
@S4ntiagoP Hello , facing a bit same errors when trying to get secrets from nanodumps output

nanodumps was runned on machine with ASCII or UTF8 language pack . And en in second lang
I made a nanodump -w (via havok) and then try use commands provided . mimikatz - both version x64, x86 , pypykatz - no luck

**Comment by S0me1-dev** [comment]
redumping with -v  gave results! possible transport corrupt dump file a bit .
